// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:nouns_flutter/models/presence_summary.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'new_match_state.freezed.dart';
// optional: Since our NewMatchState class is serializable, we must add this line.
// But if NewMatchState was not serializable, we could skip it.
part 'new_match_state.g.dart';

@freezed
class NewMatchState with _$NewMatchState {
  const factory NewMatchState(
      {required String alias,
      required List<String> categories,
      required int rounds,
      required int difficulty,
      required String host,
      required Map<String, PresenceSummary> presencesSummary}) = _NewMatchState;

  factory NewMatchState.fromJson(Map<String, Object?> json) =>
      _$NewMatchStateFromJson(json);
}
