// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:nouns_flutter/models/presence_summary.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'player_round_ranking.freezed.dart';
// optional: Since our PlayerRoundRanking class is serializable, we must add this line.
// But if PlayerRoundRanking was not serializable, we could skip it.
part 'player_round_ranking.g.dart';

@freezed
class PlayerRoundRanking with _$PlayerRoundRanking {
  const factory PlayerRoundRanking({
    required int score,
    required int ranking,
    required PresenceSummary user,
  }) = _PlayerRoundRanking;

  factory PlayerRoundRanking.fromJson(Map<String, Object?> json) =>
      _$PlayerRoundRankingFromJson(json);
}
