// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'presence_summary.freezed.dart';
// optional: Since our PresenceSummary class is serializable, we must add this line.
// But if PresenceSummary was not serializable, we could skip it.
part 'presence_summary.g.dart';

@freezed
class PresenceSummary with _$PresenceSummary {
  const factory PresenceSummary({
    required String avatar,
    required String country,
    required String userId,
    required String username,
  }) = _PresenceSummary;

  factory PresenceSummary.fromJson(Map<String, Object?> json)
      => _$PresenceSummaryFromJson(json);
}