// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBowA64n_G5t9HNk7DqgPKLl1hHgHUdybg',
    appId: '1:118525661433:android:c2ecb922531ef7b50d9228',
    messagingSenderId: '118525661433',
    projectId: 'nouns-d1b26',
    databaseURL: 'https://nouns-d1b26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nouns-d1b26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZgTy5OA_lXss8IhtRJN1Ve-5MjwsqB0',
    appId: '1:118525661433:ios:0bb2b4c3004aca460d9228',
    messagingSenderId: '118525661433',
    projectId: 'nouns-d1b26',
    databaseURL: 'https://nouns-d1b26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nouns-d1b26.appspot.com',
    androidClientId: '118525661433-450v3ah7krgt98a7072tcrq15kgqeocq.apps.googleusercontent.com',
    iosClientId: '118525661433-n1r3apctp5vmpr2n1p9m1u9vino81q00.apps.googleusercontent.com',
    iosBundleId: 'com.Dash-Studios.NounsFlutter',
  );
}
